### ISSUE TITLE
Config UI is broken in several ways

### ISSUE THREAD

**Issue by tmprnc** [isXander/YetAnotherConfigLib#105]
I don't know if this is an issue intrinsic to YACL or a mod compatibility problem, or somesuch.
When trying to go to the config for any mod that uses YACL, there is no save button. Clicking any other tab than the default one results in a UI where there is nothing displayed, including if you return to the default tab. It occurred on Wakes, and it occurred on Dynamic Crosshair.

![2023-09-02_16 58 43](https://github.com/isXander/YetAnotherConfigLib/assets/3785923/271c4818-b8c1-48be-bc09-25adcbb8ad8f)
![2023-09-02_17 08 01](https://github.com/isXander/YetAnotherConfigLib/assets/3785923/170be446-b7fc-4c8e-bcf0-f890082514fb)

Only by pressing escape (provided you haven't modified the values) can you return to the game in a working state. If you did modify any values, then alt-F4 is your only option to get out of here (which naturally results in the settings not being saved.)

I'm not sure what could be possibly causing this, if this is another mod causing it. Off the top of my head, that could affect this, I have Mod Menu, Bedrockify, Forge Config API Port, Cloth Config, owo, YACL, Sodium + Iris. I can tell you about the entire mod list if you need it. Everything is running on the very latest version of Quilt (0.20.2), on 1.20.1.

I tried modifying my settings for Wakes via a settings.json file in the config folder in interim, but I notice the folder isn't populated with a default one before you make any modifications. Therefore, changing the settings is fundamentally impossible.

Nothing is really output in the log when this happens. All I have is this, which I think is from Mod Menu and not the mod specifically.
`[17:11:45] [Render thread/ERROR]: Invalid mod icon for icon source dungeons_arise: img.png
java.lang.IllegalStateException: Must be square icon
	at org.apache.commons.lang3.Validate.validState(Validate.java:817) ~[transformed-mod-geckolib.i0:0/:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler.createIcon(FabricIconHandler.java:36) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:161) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.getIconTexture(ModListEntry.java:130) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:59) ~[transformed-mod-modmenu.i0:0/:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:244) ~[transformed-mod-modmenu.i0:0/:?]
	at net.minecraft.class_350.method_25394(class_350.java:227) ~[transformed-mod-minecraft.i0:0/:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:285) ~[transformed-mod-modmenu.i0:0/:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[17:11:46] [Render thread/INFO]: Generating YACL screen`

**Comment by isXander** [comment]
This is the fault of Bedrockify.
