### ISSUE TITLE
Crash whenever I open a configuration screen

### ISSUE THREAD

**Issue by ImNotStable** [isXander/YetAnotherConfigLib#118]
```
Reported exception thrown!
net.minecraft.class_148: Ticking screen
	at net.minecraft.class_437.method_25412(class_437.java:419)
	at net.minecraft.class_310.method_1574(class_310.java:1925)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_8088.method_48617()'
	at dev.isxander.yacl3.gui.YACLScreen.method_25393(YACLScreen.java:125)
	at net.minecraft.class_310.method_1572(class_310.java:1925)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	... 7 more
20:03:52.538
game
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-10-11 20:03:52
Description: Ticking screen

java.lang.NoSuchMethodError: 'void net.minecraft.class_8088.method_48617()'
	at dev.isxander.yacl3.gui.YACLScreen.method_25393(YACLScreen.java:125)
	at net.minecraft.class_310.method_1572(class_310.java:1925)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_310.method_1574(class_310.java:1925)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.isxander.yacl3.gui.YACLScreen.method_25393(YACLScreen.java:125)
	at net.minecraft.class_310.method_1572(class_310.java:1925)
	at net.minecraft.class_437.method_25412(class_437.java:414)

-- Affected screen --
Details:
	Screen name: dev.isxander.yacl3.gui.YACLScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_310.method_1574(class_310.java:1925)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
```
-- Affected level --
Details:
	All players: 7 total; [class_746['ImNotStable'/1425, l='ClientLevel', x=49.64, y=92.75, z=2.87], class_745['Ice_cream_fan'/1031, l='ClientLevel', x=47.83, y=81.00, z=-18.26], class_745['CIT-217db854da1a'/109, l='ClientLevel', x=61.50, y=63.00, z=8.50], class_745['CIT-99b278233b20'/129, l='ClientLevel', x=72.50, y=63.00, z=0.50], class_745['CIT-a29b97316055'/101, l='ClientLevel', x=57.50, y=63.00, z=9.50], class_745['�e[Get Crates]'/82, l='ClientLevel', x=47.50, y=63.00, z=9.50], class_745['.Theleast47'/1374, l='ClientLevel', x=54.87, y=64.00, z=-5.69]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (53,65,-11), Section: (at 5,1,5 in 3,4,-1; chunk contains blocks 48,-64,-16 to 63,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 48905864 game time, 54000 day time
	Server brand: Minehut/Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:451)
	at net.minecraft.class_310.method_1587(class_310.java:2481)
	at net.minecraft.class_310.method_1514(class_310.java:875)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, file/Crops.zip, file/Font.zip, file/Dark Mode.zip, server

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
```
```
Fabric Mods: 
		async-pack-scan: Async Pack Scan 0.2.1
		better-suggestions: Better Suggestions 1.2.0
		betterbeds: Better Beds 1.3.0
		boatiview: Boat Item View Fabric 0.0.5
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.21
		carpet: Carpet Mod 1.4.121+v231011
		chatpatches: Chat Patches 202.5.6
		cloth-config: Cloth Config v12 12.0.109
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.5.0
		continuity: Continuity 3.0.0-beta.4+1.20.2
		debugify: Debugify 1.20.2+1.0
		detailab: Detail Armor Bar 2.6.3+1.20.2-fabric
		dynamic_fps: Dynamic FPS 3.2.1
		easyvillagertrade: EasyVillagerTrade 1.2-1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		exordium: Exordium 1.2.1-mc1.20.2
		fabric-api: Fabric API 0.90.0+1.20.2
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
		fabricloader: Fabric Loader 0.14.23
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.2
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 6.0.0
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.1.1
		fsb-interop: FabricSkyBoxes Interop 1.3.5+mc1.20.2-build.49
		immediatelyfast: ImmediatelyFast 1.2.6+1.20.2
		indium: Indium 1.0.27+mc1.20.1
		iris: Iris 1.6.9
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.4
		lazydfu: LazyDFU 0.1.3
		libjf: LibJF 3.13.1
		lithium: Lithium 0.12.0
		minecraft: Minecraft 1.20.2
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		modernfix: ModernFix 5.8.1+mc1.20.2
		modmenu: Mod Menu 8.0.0
		moreculling: More Culling 1.20.1-0.19.0
		morecullingextra: More Culling Extra 1.1-1.20.1
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		noxesium: Noxesium 1.0.5+f253e35
		nvidium: Nvidium 0.2.0-beta
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.2-build.96
		skinlayers: 3d Skin Layers 1.5.6-mc1.20.2
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.2+mc1.20.2-build.113
		starlight: Starlight 1.1.2+fabric.bdaeb21
		threadtweak: ThreadTweak 1.20.2-0.1.1
		uglyscoreboardfix: Ugly Scoreboard Fix 2.10.1
		viafabric: ViaFabric 0.4.11+47-dev
		vmp: Very Many Players 0.2.0+beta.7.117
		waveycapes: WaveyCapes 1.3.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
		zoomify: Zoomify 2.12.0
```

**Comment by ImNotStable** [comment]
?

**Comment by isXander** [comment]
Looks like you're using the incorrect version of YACL. If you're on 1.20.2, there is a specific build for that version.
