### ISSUE TITLE
[Bug Report] BufferedFileImageInputStreamSpi not found in 1.20.5 version

### ISSUE THREAD

**Issue by oliviathevampire** [isXander/YetAnotherConfigLib#172]
I get this issue when trying to run in dev 
```
[20:22:52] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.20.5 with Fabric Loader 0.15.10
[20:22:52] [ForkJoinPool-1-worker-1/WARN] (FabricLoader/Metadata) Mod obsidian uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:22:54] [main/WARN] (FabricLoader/Resolution) Mod resolution failed
[20:22:54] [main/INFO] (FabricLoader/Resolution) Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED fabric-api 0.97.6+1.20.5 {depends java @ [>=21]}, ROOT_FORCELOAD_SINGLE fabric-api 0.97.6+1.20.5]
[20:22:54] [main/INFO] (FabricLoader/Resolution) Reason: [HARD_DEP fabric-api 0.97.6+1.20.5 {depends java @ [>=21]}]
[20:22:54] [main/INFO] (FabricLoader/Resolution) Fix: add [], remove [], replace [[java 17] -> add:java 21 ([[21,∞)])]
[20:22:54] [main/ERROR] (FabricLoader) Incompatible mods found!
 net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.
More details:
	 - Mod 'Fabric API' (fabric-api) 0.97.6+1.20.5 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[20:22:55] [main/WARN] (FabricLoader) Failed to open the error gui!
 java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1369) ~[?:?]
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344) ~[?:?]
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open0(FabricMainWindow.java:94) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open(FabricMainWindow.java:88) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.open(FabricGuiEntry.java:51) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:141) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:108) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:84) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.util.ServiceConfigurationError: javax.imageio.spi.ImageInputStreamSpi: Provider com.twelvemonkeys.imageio.stream.BufferedFileImageInputStreamSpi not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593) ~[?:?]
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219) ~[?:?]
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:185) ~[?:?]
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113) ~[?:?]
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134) ~[?:?]
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.loadImage(FabricMainWindow.java:225) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.createUi(FabricMainWindow.java:109) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.lambda$open0$0(FabricMainWindow.java:95) ~[fabric-loader-0.15.10.jar:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:308) ~[?:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Disconnected from the target VM, address: '127.0.0.1:49441', transport: 'socket'

Process finished with exit code 1
```

**Comment by isXander** [comment]
> Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.

**Comment by oliviathevampire** [comment]
I am running java 21
