### ISSUE TITLE
Deserializing YACLConfig crash!

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [isXander/YetAnotherConfigLib#189]
Last Log Line : 
Deserializing YACLConfig from 'C:\Users\Jonas\AppData\Roaming\com.modrinth.theseus\profiles\Fabulously Fresh\config\yacl.json5'
Crash Report :
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-06-28 18:46:05
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'moonlight'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "dev.isxander.yacl3.config.v2.api.ConfigClassHandler.instance()" because the return value of "dev.imb11.sounds.config.utils.ConfigGroup.getHandler()" is null
	at dev.imb11.sounds.config.SoundsConfig.get(SoundsConfig.java:50)
	at dev.imb11.sounds.api.config.TagPair.handleTagPair(TagPair.java:69)
	at net.minecraft.class_2248.handler$kaa000$sounds$$manageCustomSounds(class_2248.java:8566)
	at net.minecraft.class_2248.method_9573(class_2248.java)
	at net.mehvahdjukaar.moonlight.api.set.BlockType.getSound(BlockType.java:255)
	at net.mehvahdjukaar.moonlight.api.set.wood.WoodType.copyProperties(WoodType.java:243)
	at net.mehvahdjukaar.suppsquared.SuppSquared.registerItemShelves(SuppSquared.java:141)
	at net.mehvahdjukaar.moonlight.core.set.fabric.BlockSetInternalImpl$LateRegQueue.lambda$registerEntries$1(BlockSetInternalImpl.java:75)
	at java.base/java.util.ArrayDeque.forEach(ArrayDeque.java:888)
	at net.mehvahdjukaar.moonlight.core.set.fabric.BlockSetInternalImpl$LateRegQueue.registerEntries(BlockSetInternalImpl.java:75)
	at net.mehvahdjukaar.moonlight.core.set.fabric.BlockSetInternalImpl.registerDynamicEntries(BlockSetInternalImpl.java:45)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegHelperImpl.lateRegisterEntries(RegHelperImpl.java:93)
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.commonSetup(MoonlightFabric.java:60)
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabricClient.onInitializeClient(MoonlightFabricClient.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more

**Comment by Zpeaxirious** [comment]
There's an easy fix for that, I went to the .json5, removed it and launched it again. Try that

**Comment by isXander** [comment]
@imb11 issue with sounds
