### ISSUE TITLE
Crash on Fabric 0.14.11 1.19.2

### ISSUE THREAD

**Issue by Poke097** [isXander/YetAnotherConfigLib#43]
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'YetAnotherConfigLib' (yet-another-config-lib) 2.1.0 with version 1.4.3 or later that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'YetAnotherConfigLib' (yet-another-config-lib) 2.1.0 requires any version between 1.19.3 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
```
	
Curseforge told me to update, and the website shows tags for 1.19.2 as well, so I was confused as to why this wasn't support

**Comment by SpigotDE** [comment]
same here

**Comment by isXander** [comment]
it's a mistake, it shouldn't be marked as 1.19.2
